version: 2.1
orbs:
  node: circleci/node@5.2.0
  docker: circleci/docker@2.2.0
  snyk: snyk/snyk@1.4.0
  artifactory: jfrog/artifactory-orb@1.0.1
jobs:
  build_and_test:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: npm run test-ci
      - run:
          name: Copy tests results for storing
          command: |
            mkdir test-results
            cp test-results.xml test-results/
          when: always
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
  dependency_vulnerability_scan:
      docker:
        - image: cimg/node:16.16.0
      steps:
        - checkout
        - node/install-packages
        - snyk/scan:
            fail-on-issues: false
            monitor-on-build: false
  build_docker_image:
      machine:
        image: ubuntu-2004:current
      steps:
        - checkout
        - run:
            name: Install jf cli
            command: |
              sudo curl -fL https://install-cli.jfrog.io | sh
              jf config add \
              --user=$ARTIFACTORY_USER \
              --access-token=$ARTIFACTORY_API_KEY \
              --url=$ARTIFACTORY_URL \
              --artifactory-url=$ARTIFACTORY_URL/artifactory \
              --distribution-url=$ARTIFACTORY_URL/distribution \
              --mission-control-url=$ARTIFACTORY_URL/ms \
              --pipelines-url=$ARTIFACTORY_URL/pipelines \
              --xray-url=$ARTIFACTORY_URL/xray \
              --interactive=false
        - run:
            name: Build Docker image
            command: |
              jf docker buildx build -t punkdata.jfrog.io/cicd-docker/cicd-workshop:<< pipeline.number >> .
        - run:
            name: Push Docker image
            command: |
              printenv |grep $DOCKER_USER && printenv |grep $DOCKER_PASSWORD
              docker login --username=$DOCKER_USER --password=$DOCKER_PASSWORD $ARTIFACTORY_URL
              jf docker push punkdata.jfrog.io/cicd-docker/cicd-workshop:<< pipeline.number >>              
        - run:
            name: Push Scan Docker image
            command: |
              docker images 
              jf docker scan punkdata.jfrog.io/cicd-docker/cicd-workshop:<< pipeline.number >>
workflows:
  test_scan_deploy:
      jobs:
        - build_and_test:
            context:
              - CICD_WORKSHOP_JFROG
        - dependency_vulnerability_scan:
            context:
              - CICD_WORKSHOP_SNYK
        - build_docker_image:
            context:
              - CICD_WORKSHOP_DOCKER
              - CICD_WORKSHOP_SNYK
